models:
  - title: Gemini 1.5 Flash
    provider: gemini
    model: gemini-1.5-flash
    apiKey: AIzaSyBU9a4wTASc3yGyXHQyMGkIe6ZzVZoFEiA
  - name: Gemini 3.1 Pro
    provider: gemini
    model: gemini-3.1-pro-preview
    apiKey: AIzaSyBU9a4wTASc3yGyXHQyMGkIe6ZzVZoFEiA
  - name: Gemini 3.1 Pro (1)
    provider: gemini
    model: gemini-3.1-pro-preview
    apiKey: AIzaSyBU9a4wTASc3yGyXHQyMGkIe6ZzVZoFEiA
  - name: Gemini 3.1 Pro (2)
    provider: gemini
    model: gemini-3.1-pro-preview
    apiKey: AIzaSyBU9a4wTASc3yGyXHQyMGkIe6ZzVZoFEiA
  - name: Gemini 3.1 Pro (3)
    provider: gemini
    model: gemini-3.1-pro-preview
    apiKey: AIzaSyBU9a4wTASc3yGyXHQyMGkIe6ZzVZoFEiA
tabAutocompleteModel:
  title: Gemini 1.5 Flash
  provider: gemini
  model: gemini-1.5-flash
  apiKey: AIzaSyBU9a4wTASc3yGyXHQyMGkIe6ZzVZoFEiA
